flags/flags/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('get_flags/', include('get_flags.urls')),
]

flags/get_flags/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'get_stuff'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('index_api/', views.index_api, name='index_api'),
	path('flags/', views.get_flags, name='flags'),
	path('flags_api/', views.get_flags_api, name='flags_api'),
	path('fav_country/', views.fav_country, name='fav_country'),
]

flags/get_flags/models.py
from django.db import models
from django.contrib.auth.models import User

class Flag(models.Model):
	country = models.CharField(max_length=100)

	def __str__(self):
		return self.country

class Color(models.Model):
	name = models.CharField(max_length=100)
	flags = models.ManyToManyField(Flag)

	def __str__(self):
		return self.name

class FavoriteFlag(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	flag = models.ForeignKey(Flag, on_delete=models.CASCADE)

class FavoriteColor(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	color = models.ForeignKey(Color, on_delete=models.CASCADE)

flags/get_flags/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Color, Flag, FavoriteColor, FavoriteFlag
import json
from django.views.decorators.csrf import csrf_exempt

def index(request):
	colors = Color.objects.all()
	context = {'colors': colors}
	return render(request, 'get_flags/index.html', context)

def index_api(request):
	colors = Color.objects.all()
	url = 'http://localhost:8000/get_flags/flags_api/'
	context = {'colors': colors, 'url': url}
	return render(request, 'get_flags/index_api.html', context)

def get_flags(request):
	color_list = request.POST.getlist('colors')
	if len(color_list) == 0:
		return HttpResponseRedirect(reverse('get:index'))
	flags = Flag.objects
	for color in color_list:
		flags = flags.filter(color=color)
	print(flags)
	context = {'flags': flags}
	return render(request, 'get_flags/flags.html', context)

def get_flags_api(request):
    color_list = request.GET.getlist('colors')
    print(color_list)
    if len(color_list) == 0:
        return HttpResponse('No Colors Selected')
    flags = Flag.objects
    name_error = False
    try:
        for color in color_list:
            flags = flags.filter(color=Color.objects.get(name=color))
    except Color.DoesNotExist:  # DoesNotExist:
        name_error = True
        flags = []
    print(flags)
    flag_list = [flag.country for flag in flags]
    context = {'flags': flag_list, 'name_error': name_error}
    return JsonResponse(context)

@csrf_exempt
def fav_country(request):
	active_user = request.user
	request_dict = json.loads(request.body)
	active_country = request_dict.get('country', None)
	# active_country = request.GET['country']
	print(active_user, active_country)
	fav_flag = FavoriteFlag(user=active_user, flag=Flag.objects.get(country=active_country))
	fav_flag.save()
	return HttpResponse('good')

flags/get_flags/templates/get_flags/flags.html
{% for flag in flags %}
  {{flag.country}}
{% endfor %}

flags/get_flags/templates/get_flags/index.html
<form action={% url 'get_stuff:flags' %} method='post'>
{% csrf_token %}
{% for color in colors %}
  <input type="checkbox" name="colors" value="{{color.id}}">{{color.name}}<br>
{% endfor %}
<button>Get Flags</button>
</form>

flags/get_flags/templates/get_flags/index_api.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
{% for color in colors %}
  <input class="colors_check" type="checkbox" name="colors" value="{{color.name}}">{{color.name}}<br>
{% endfor %}
<button id='get_flags'>Get Flags</button>
<div id='country_text' style='height:50px'></div>

<script>
  get_flags = document.querySelector("#get_flags")
  colors = document.querySelectorAll(".colors_check")
  country_text = document.querySelector("#country_text")
  get_flags.onclick = function() {
	//url = "{{ url }}" + '?' + Array.from(colors, color => `colors=${color.value}`).join('&')
 	url = "{{ url }}?" + Array.from(colors, color => (color.checked) ? `colors=${color.value}`: "" ).join("&")
	//url = "{{ url }}" + '?' + colors.map(color => `color=${color}`).join('&')
	//console.log(Array.from(colors, color => `color=${color}`).join('&'))
    axios.get(url)
    .then(function(response) {
	  console.log(response.data)
	  for (let i=0; i<response.data.flags.length; i++) {
		new_span = document.createElement('span')
		new_span.innerText = response.data.flags[i]
		country_text.appendChild(new_span)
		new_btn = document.createElement('button')
		new_btn.innerText = 'Save'
		new_btn.onclick = function() {
		  axios({
			method: 'post',
			url: '{% url "get_stuff:fav_country" %}',
			data: {
	         	country: response.data.flags[i],
                        headers: {
                          'X-CSRFToken': '{{ csrf_token }}'
                        }
		    },
		  })
		  .then(function (response) {
		    console.log(response);
		  })
		}
		country_text.appendChild(new_btn)
		new_br = document.createElement('br')
		country_text.appendChild(new_br)
	  }
	})
  
  
  }
</script>

flags/get_flags/templates/get_flags/test1.html
<html>
  <head>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  </head>
  <body>
    <script>
	  /*
      let url = '{% url "get_stuff:fav_country" %}'
      let data = {country: 'USA',}
      let headers = {"X-CSRFToken": "{{csrf_token}}"}
      axios.post(url, {'params': data}, {'headers': headers})
      .then(function(response) {
        console.log(response)
      
      })
      */
      axios({
        method: "POST",
        url: '{% url "get_stuff:fav_country" %}',
        data: {
          'country': 'USA',
        },
        headers: {"X-CSRFToken": "{{csrf_token}}"},
      })
      .then(function(response) {
        console.log(response)
	  
      })
    </script>
  </body>
</html>